# Generated by Django 3.1.7 on 2021-04-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
    ]
