# Generated by Django 3.1.7 on 2021-04-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_persona_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infocontacto', to='personas.persona')),
            ],
        ),
    ]
