# Generated by Django 3.1.7 on 2021-04-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='name',
            new_name='nombre',
        ),
    ]
