# Generated by Django 3.1.7 on 2021-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='personas',
            field=models.ManyToManyField(related_name='videos', to='personas.Persona'),
        ),
    ]
