# Generated by Django 3.1.7 on 2021-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_calificacion_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
